"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { ensureAnonymousSession, getSupabase } from "@/lib/supabase";
import type { Question, RoundSummary } from "@/lib/types";

type Phase="lobby"|"question"|"reveal"|"ended";
type Room={id:string;phase:Phase;current_round:number;max_rounds:number};
type Player={id:string;user_id:string;name:string;avatar:string;points:number};
type Round={id:string;number:number;duration_seconds:number;started_at:string;revealed_at:string|null;host_line:string;question:Question};
type Answer={player_id:string;choice:number;is_correct:boolean};

export default function RoomPage(){
 const {code:raw}=useParams<{code:string}>(), code=raw.toUpperCase();
 const router=useRouter(), isHost=useSearchParams().get("host")==="1";
 const [room,setRoom]=useState<Room|null>(null),[players,setPlayers]=useState<Player[]>([]),[round,setRound]=useState<Round|null>(null),[answers,setAnswers]=useState<Answer[]>([]);
 const [uid,setUid]=useState(""),[myAnswer,setMyAnswer]=useState<number|null>(null),[status,setStatus]=useState("conectando…"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{
  const rid=sessionStorage.getItem("kairos_room_id"); if(!rid){router.replace(`/?join=${code}`);return}
  const db=getSupabase();
  const [rr,pp,rounds]=await Promise.all([db.from("rooms").select("id,phase,current_round,max_rounds").eq("id",rid).single(),db.from("players").select("id,user_id,name,avatar,points").eq("room_id",rid).order("points",{ascending:false}),db.from("rounds").select("id,number,duration_seconds,started_at,revealed_at,host_line,question:questions(*)").eq("room_id",rid).order("number",{ascending:false}).limit(1)]);
  if(rr.error)throw rr.error; setRoom(rr.data as Room);setPlayers((pp.data??[]) as Player[]);
  const current=rounds.data?.[0] as unknown as Round|undefined;setRound(current??null);
  if(current){const aa=await db.from("answers").select("player_id,choice,is_correct").eq("round_id",current.id);setAnswers((aa.data??[]) as Answer[])}else setAnswers([]);
 },[code,router]);
 useEffect(()=>{let channel:ReturnType<ReturnType<typeof getSupabase>["channel"]>|null=null;
  ensureAnonymousSession().then(async s=>{if(!s)throw Error("No se pudo iniciar la sesión");setUid(s.user.id);await load();const rid=sessionStorage.getItem("kairos_room_id")!;
   channel=getSupabase().channel(`kairos:${rid}`).on("postgres_changes",{event:"*",schema:"public",table:"rooms",filter:`id=eq.${rid}`},load).on("postgres_changes",{event:"*",schema:"public",table:"players",filter:`room_id=eq.${rid}`},load).on("postgres_changes",{event:"*",schema:"public",table:"rounds",filter:`room_id=eq.${rid}`},load).on("postgres_changes",{event:"*",schema:"public",table:"answers"},load).subscribe(s=>setStatus(s==="SUBSCRIBED"?"en vivo":s==="CHANNEL_ERROR"?"sin conexión":"conectando…"));
  }).catch(e=>setError(e.message)); return()=>{if(channel)void getSupabase().removeChannel(channel)};
 },[load]);
 useEffect(()=>{const me=players.find(p=>p.user_id===uid);setMyAnswer(answers.find(a=>a.player_id===me?.id)?.choice??null)},[answers,players,uid]);

 async function next(){if(!room||busy)return;setBusy(true);setError("");try{
  if(room.current_round>=room.max_rounds){const x=await getSupabase().from("rooms").update({phase:"ended"}).eq("id",room.id);if(x.error)throw x.error;return}
  const old=await getSupabase().from("rounds").select("question_id").eq("room_id",room.id),askedIds=(old.data??[]).map(x=>x.question_id);
  const summary:RoundSummary={correctRate:answers.length?answers.filter(a=>a.is_correct).length/answers.length:0,playerCount:players.length,askedIds,lastDifficulty:round?.question.difficulty??null};
  const response=await fetch("/api/host",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(summary)});if(!response.ok)throw Error("El anfitrión no pudo preparar el reto");const data=await response.json();
  if(data.done){await getSupabase().from("rooms").update({phase:"ended"}).eq("id",room.id);return}
  const inserted=await getSupabase().from("rounds").insert({room_id:room.id,number:room.current_round+1,question_id:data.question.id,host_line:data.hostLine,duration_seconds:15});if(inserted.error)throw inserted.error;
  const updated=await getSupabase().from("rooms").update({phase:"question",current_round:room.current_round+1,updated_at:new Date().toISOString()}).eq("id",room.id);if(updated.error)throw updated.error;
 }catch(e){setError(e instanceof Error?e.message:"No pudimos iniciar la ronda")}finally{setBusy(false)}}
 async function answer(choice:number){if(!round||myAnswer!==null||room?.phase!=="question")return;setMyAnswer(choice);const elapsed=Date.now()-new Date(round.started_at).getTime();const x=await getSupabase().rpc("submit_answer",{target_round:round.id,selected_choice:choice,elapsed});if(x.error){setMyAnswer(null);setError("La respuesta no se registró o el tiempo terminó")}}
 async function reveal(){if(!room||!round)return;const now=new Date().toISOString(),a=await getSupabase().from("rounds").update({revealed_at:now}).eq("id",round.id).is("revealed_at",null);if(a.error){setError(a.error.message);return}await getSupabase().from("rooms").update({phase:"reveal",updated_at:now}).eq("id",room.id)}

 if(!room)return <main className="grid min-h-dvh place-items-center text-center"><div className="text-5xl">🕯️<p className="mt-4 text-base text-lilac">{error||"Preparando la sala…"}</p></div></main>;
 return <main className="mx-auto min-h-dvh max-w-md px-5 py-6"><header className="mb-5 flex justify-between"><div><small className="font-mono uppercase tracking-[.3em] text-lilac">Sala</small><div className="font-mono text-2xl font-bold tracking-[.35em] text-candle">{code}</div></div><div className="h-fit rounded-full border border-white/10 bg-night-2 px-3 py-2 text-xs"><span className="mr-2 text-ember">●</span>{players.length} · {status}</div></header>
 {error&&<p role="alert" className="mb-4 rounded-xl border border-ember/40 bg-ember/10 p-3 text-sm">{error}</p>}
 {room.phase==="lobby"&&<Lobby players={players} code={code} host={isHost} busy={busy} start={next}/>} {(room.phase==="question"||room.phase==="reveal")&&round&&<Play room={room} round={round} answers={answers} mine={myAnswer} host={isHost} busy={busy} answer={answer} reveal={reveal} next={next}/>} {room.phase==="ended"&&<Results players={players} exit={()=>router.push("/")}/>}<footer className="mt-8 text-center text-[10px] uppercase tracking-[.2em] text-lilac/50">Texto bíblico · Reina-Valera 1909 · Dominio público</footer></main>
}

function Lobby({players,code,host,busy,start}:{players:Player[];code:string;host:boolean;busy:boolean;start:()=>void}){const[copied,setCopied]=useState(false);async function share(){await navigator.clipboard?.writeText(`${location.origin}/?join=${code}`);setCopied(true);setTimeout(()=>setCopied(false),1500)}return <section className="rise"><div className="rounded-3xl border border-candle/20 bg-gradient-to-br from-candle/10 to-night-2 p-6 text-center"><div className="text-5xl">🕯️</div><h1 className="mt-3 font-display text-3xl font-bold">La familia se reúne</h1><p className="mt-2 text-sm text-lilac">Comparte el código y prepárense para jugar.</p><button onClick={share} className="mt-4 rounded-xl border border-white/15 px-4 py-2 text-sm">{copied?"¡Enlace copiado!":"Compartir invitación"}</button></div><h2 className="mb-3 mt-6 font-mono text-xs uppercase tracking-widest text-lilac">Jugadores · {players.length}</h2><div className="grid grid-cols-3 gap-2">{players.map(p=><div key={p.id} className="pop rounded-2xl border border-white/10 bg-night-2/70 p-3 text-center"><div className="text-3xl">{p.avatar}</div><div className="mt-1 truncate text-xs">{p.name}</div></div>)}</div>{host?<button disabled={busy} onClick={start} className="mt-8 w-full rounded-xl bg-candle py-4 font-bold text-night shadow-halo-lg disabled:opacity-50">{busy?"Preparando reto…":"Comenzar partida"}</button>:<p className="mt-8 text-center text-lilac">Esperando al anfitrión…</p>}</section>}

function Play({room,round,answers,mine,host,busy,answer,reveal,next}:{room:Room;round:Round;answers:Answer[];mine:number|null;host:boolean;busy:boolean;answer:(n:number)=>void;reveal:()=>void;next:()=>void}){const[now,setNow]=useState(Date.now());useEffect(()=>{if(room.phase!=="question")return;const t=setInterval(()=>setNow(Date.now()),100);return()=>clearInterval(t)},[room.phase]);const left=Math.max(0,round.duration_seconds-(now-new Date(round.started_at).getTime())/1000),tallies=useMemo(()=>[0,1,2,3].map(i=>answers.filter(a=>a.choice===i).length),[answers]),revealed=room.phase==="reveal",colors=["#7B6CF6","#FF6B5E","#F5C451","#5EC6A8"];return <section className="rise"><div className="mb-5 rounded-2xl border border-candle/20 bg-candle/10 p-4"><small className="font-mono uppercase tracking-widest text-candle">Anfitrión KAIROS</small><p className="mt-1 text-sm">{round.host_line}</p></div><div className="mb-3 flex justify-between font-mono text-xs uppercase text-lilac"><span>Ronda {round.number}/{room.max_rounds}</span><span className="text-candle">{round.question.reference}</span></div>{!revealed&&<div className="mb-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-candle" style={{width:`${left/round.duration_seconds*100}%`}}/></div>}<h1 className="mb-6 text-center font-display text-2xl font-bold">{round.question.prompt}</h1><div className="space-y-3">{round.question.options.map((o,i)=>{const correct=revealed&&i===round.question.correct,chosen=mine===i;return <button key={o} disabled={revealed||mine!==null||left<=0} onClick={()=>answer(i)} className={`w-full rounded-2xl border p-4 text-left font-semibold ${correct?"border-emerald-300 bg-emerald-400/25":chosen?"border-candle bg-candle/20":"border-white/10 bg-night-2"}`}><span className="mr-3 inline-grid h-8 w-8 place-items-center rounded-lg text-night" style={{backgroundColor:colors[i]}}>{String.fromCharCode(65+i)}</span>{o}{revealed&&<span className="float-right text-lilac">{tallies[i]}</span>}</button>})}</div>{mine!==null&&!revealed&&<p className="mt-5 text-center text-candle">¡Respuesta guardada! Esperando…</p>}{host&&room.phase==="question"&&<button onClick={reveal} className="mt-6 w-full rounded-xl border border-candle/40 py-3 text-candle">Mostrar respuesta</button>}{revealed&&host&&<button disabled={busy} onClick={next} className="mt-6 w-full rounded-xl bg-candle py-4 font-bold text-night">{busy?"Preparando…":"Siguiente reto"}</button>}</section>}
function Results({players,exit}:{players:Player[];exit:()=>void}){return <section className="rise text-center"><div className="text-6xl">🏆</div><h1 className="mt-3 font-display text-4xl font-bold text-candle">¡Momento de celebrar!</h1><p className="mt-2 text-lilac">Aprendieron y compartieron juntos.</p><div className="mt-7 space-y-2 text-left">{players.map((p,i)=><div key={p.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-night-2 p-4"><b className="w-7 text-candle">#{i+1}</b><span className="text-2xl">{p.avatar}</span><span className="flex-1">{p.name}</span><b>{p.points} pts</b></div>)}</div><button onClick={exit} className="mt-7 w-full rounded-xl bg-candle py-4 font-bold text-night">Volver al inicio</button></section>}
